[package]
name = "rustblockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
chrono = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"